export const SET_STATUS = 'SET_STATUS'
export const SET_LETTERS = 'SET_LETTERS'
export const SET_SELECTED = 'SET_SELECTED'
export const SET_WORD = 'SET_WORD'
export const SET_NEW_GAME = 'SET_NEW_GAME'
export const ADD_WORD = 'ADD_WORD'
export const DELETE_WORD = 'DELETE_WORD'
