const SET_STATUS = 'SET_STATUS'
const SET_LETTERS = 'SET_LETTERS'
const SET_WORD = 'SET_WORD'
const ADD_WORD = 'ADD_WORD'
const DELETE_WORD = 'DELETE_WORD'

export { SET_STATUS, SET_LETTERS, SET_WORD, ADD_WORD, DELETE_WORD }
